# Default configuration

spring:
    profiles:
        active: dev
    main:
        banner-mode: "off"
custom:
    system:
        wall-length: 0.5
        small-particles-radius: 0.005
        small-particles-mass: 0.001
        big-particle-mass: 0.1
        big-particle-radius: 0.05


---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development


logging:
    config: classpath:logging/logback-spring-dev.xml

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production

logging:
    config: classpath:logging/logback-spring-prod.xml